server:
  port: 8082
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet


  datasource:
    url: jdbc:postgresql://localhost:5432/BankingSystem
    username: postgres
    password: Mariam2905

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true